version: "2.0"
services:
  testrpc:
    image: dougvk/testrpc:latest
    command: bash -c "testrpc"
    ports:
      - "8545:8545"
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "8080:8080"
      - "5001:5001"
      - "4001:4001"
  app:
    image: transmute-web-app-starter-kit-docker
    ports:
      - "3000:3000"
    environment:
      - RPC_HOST=testrpc
    links: 
      - "ipfs:ipfs"
      - "testrpc:testrpc"
  
